package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "project-graphs"
                id = "PROJECT_EXT_6"
                param("series", """
                    [
                      {
                        "type": "valueType",
                        "title": "Success Rate",
                        "sourceBuildTypeId": "AngularCliApp_Build",
                        "key": "SuccessRate"
                      }
                    ]
                """.trimIndent())
                param("format", "text")
                param("hideFilters", "")
                param("title", "Build Success Rate")
                param("defaultFilters", "")
                param("seriesTitle", "Serie")
            }
        }
    }
}
